const quotes = [
  "text the person who ghosted u, 'what are we?'",
  "screenshot someone's snapchat profile who u barely know.",
  "video call an inactive snapchat group chat.",
  "go on instagram live and stare at the camera for two minutes.",
  "unarchive an old post and repost it on ur story for 10 mins.",
  "screenshot a post on someone’s page and repost it on ur main feed for 10 mins.",
  "start a fight in the comments of the first tiktok on ur FYP.",
  "let the person u phubbed pick a random person ur following on instagram and like all of their posts.",
  "send a voice message to someone u haven't spoken to in years, pretending like u never lost touch.",
  "let the person u phubbed search whatever word they want in ur messages.",
  "direct message someone from high school pretending u want to be their sugar daddy.",
  "create a fictional event on facebook and invite all ur friends to it. make it as outrageous as possible.",
  "post on ur instagram story asking for podiatrist recommendations for 5 mins.",
  "comment a pickup line on a celebrity’s instagram post.",
  "post a screenshot of u listening to episode 3 of the 'call her daddy' podcast and caption it '10/10 recommend.'",
  "post the cover of the book 'fifty shades of grey' on ur story and caption it 'light reading.' keep it up for 10 mins.",
  "post a photo of nick wilde from zootopia on ur story and caption it 'smash' and leave it there for 10 mins.",
  "pick a random person in ur snapchat and just start typing without sending anything until they say something.",
  "post a video on ur instagram story recapping every tiny detail of ur day.",
  "post on ur instagram story admitting u don’t entirely understand how to read time off a clock. leave it there for 30 mins.",
  "post on ur story that ur selling two tickets to fyre festival. delete it after 1 hr.",
  "screenshot ur snap map and post it on ur instagram story with the caption, 'i don’t leave the house until i check this.' leave it up for 10 mins.",
  "post a photo of ur family on ur instagram story and put an inappropriate song over it.",
  "post on ur instagram story asking people who have experience going out with furries to swipe up.",
  "call the 12th person in ur contacts and start singing in cursive. leave a voicemail if u have to.",
  "facetime ur crush through instagram.",
  "find a random story on instagram, recreate it to look identical, and post that on ur story for 2 hrs.",
  "record urself doing the fortnite dance and post it on ur story for 5 min.",
  "film urself making ur 'go-to' snack tutorial, but it’s actually the weirdest combo. post it on ur story and leave it there for 10 mins.",
  "film urself singing terribly and caption it 'finally showing u guys what I can do <3.' post it on ur story for 5 min.",
  "post something TMI on ur instagram story and then post another story after saying 'oops sorry that was for my private.' keep both posts up for 10 mins.",
  "post a feet pic with an emoji covering most of the pic on ur story. caption it 'swipe up for price' and leave it there for 5 mins",
  "send a voice memo of urself screaming to the 27th person in ur contacts.",
  "post an instagram story of a black screen and type in 'don’t hmu. real ones know…' and leave it up for 30 mins.",
  "comment on the first celeb’s post u see on instagram saying 'i love ur confidence!'",
  "go to ur snapchat and post ur 'flashback' from over 3 years ago on ur main story. keep it up for 2 hours.",
  "record urself talking in a cosplay voice with hand gestures and post it on ur instagram story for 5 mins.",
  "post a screenshot of u watching a nikocado avacado youtube video and caption it 'fav youtuber!' on ur instagram story. leave it there for 10 mins.",
  "post a question on ur instagram story captioned 'writing a fanfiction about harry styles but kind of having writer's block. any ideas?' leave it there for 10 mins.",
  "find a celebrity fan edit instagram and repost one of the thirst trap edits to ur main instagram story for 10 min",
  "screenshot ur friend’s recent instagram post and text it to them. send another text saying 'wrong person!'",
  "call pizza hut and ask about 'their menu,' but just start asking about the Domino's menu.",
  "call pink whitney’s customer service and tell them u want a refund bc u woke up this morning in a different state (u are very distraught).",
  "post the 65th photo in ur camera roll on ur Instagram story for 10 minutes.",
  "call the skims customer service and ask if their clothes come with a free BBL.",
  "call the 41st person in ur contacts and confess ur love for them.",
  "let the person u phubbed post one of ur TikTok drafts set to 'anyone can view.'",
  "text ur parents that u got engaged to someone u met last night.",
  "text a friend u haven’t talked to in 1+ years 'i see u.'",
  "text someone random about how ur so happy that u two are so close.",
  "post an embarrassing picture of urself from middle school and act like it was taken yesterday. leave it up for 10 mins.",
  "add someone ur not close with to ur close friends story on instagram. leave them there.",
  "draw a zero-effort picture and post it onto ur instagram story with a poll that asks people if they like ur art.",
  "grab the first item u see. then act as if ur an influencer and post a review of that product on ur story. leave it up for 10 mins.",
  "call a person u wanted to room with before college on instagram (must be someone u didn’t end up rooming with).",
  "write a fake apology post about being 'cancelled' and post it on ur close friends/private story. leave it up for 30 mins.",
  "text ur main group chat that they should probably stop phubbing.",
  "snapchat an old crush. *bonus points if they knew u liked them",
  "change ur profile picture to the last embarrassing picture u took of urself for 30 minutes.",
  "post the last picture on ur camera roll to ur instagram story. leave it up for 10 mins.",
  "post any picture on ur instagram story, but add an embarrassing song to it.",
  "text the last person in ur contacts a random emoji.",
  "call a random number and tell them u accidentally clogged their toilet.",
  "make an acting tiktok and post it for 20 mins.",
  "post the first thing from ur snapchat memories to ur main story and keep it up for 30 mins.",
  "go live on instagram for 5 mins and let the person u phubbed invite a random person to join.",
  "allow the person u phubbed to post a random picture of u on ur story. leave it up for 10 minutes.",
  "loudly play an embarrassing song or ringtone in a public place.",
  "have someone take a 0.5 photo of u and post it without checking. leave it up for 30 mins.",
  "follow and then unfollow someone u haven’t talked to in a while on instagram.",
  "share a screenshot of ur current search history with the person u phubbed.",
  "share an embarrassing childhood photo on social media.",
  "send a love poem text to an old crush on snapchat.",
  "have the person u phubbed choose someone ur following. like their oldest photo on instagram.",
  "view a random person's instagram highlights and like their story.",
  "call a contact and sing 'happy birthday' to them. the phubbed gets to choose who.",
  "text a friend and say you’ve adopted a pet and need them to pet-sit it.",
  "call ur parents and tell them u got pulled over for going over the speed limit.",
  "send a text to a friend and tell them u are expecting a baby.",
  "scream 'i don’t like this game' out loud.",
  "post on ur story, 'new phone, who this?' leave it up for 10 mins.",
  "type something on snapchat to ur old crush, then delete before sending.",
  "send a pickup line to an old crush, but don’t respond.",
  "post the oldest photo in ur camera roll to ur story and leave it there for 10 mins.",
  "post a picture of ur pet and caption it 'for sale, swipe up, serious inquiries only.' on your story and leave it there for 10 mins.",
  "let the person next to u send a text to the last person u texted.",
  "post a picture of ur favorite celebrity and caption it 'R.I.P.' leave it up for 10 mins.",
  "call a parent and tell them their favorite celebrity died.",
  "post a picture of u and ur ex. leave it up for 5 mins.",
  "post a video of u doing the chicken dance on ur story. leave it up for 5 mins.",
  "post ur biggest hot take on ur story. leave it up for 30 mins."
];

const quoteContainer = document.getElementById('quote-text');
const randomIndex = Math.floor(Math.random() * quotes.length);

quoteContainer.innerText = quotes[randomIndex];